# Generated by Django 4.1.3 on 2023-01-02 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface', models.FloatField()),
                ('prix', models.IntegerField(max_length=10000)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('categories', models.CharField(choices=[('V', 'Vente'), ('E', 'Echange'), ('L', 'Location'), ('LV', 'Location pour vacance')], max_length=50)),
                ('types', models.CharField(choices=[('T', 'Terrain'), ('TA', 'Terrain Agricole'), ('A', 'Appartement'), ('M', 'Maison'), ('B', 'Bungalow')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('commune', models.CharField(max_length=25)),
                ('adresse', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('wil', models.CharField(choices=[('Adrar', 'Adrar'), ('chlef', 'chlef'), ('Laghouat', 'Laghouat'), ('Oum-El-bouaghi', 'Oum-El-bouaghi'), ('Batna', 'Batna'), ('Bejaia', 'Bejaia'), ('Biskra', 'Biskra'), ('Bechar', 'Bechar'), ('Blida', 'Blida'), ('Bouira', 'Bouira'), ('Tamanrasset', 'Tamanrasset'), ('Tebessa', 'Tebessa'), ('Tlemcen', 'Tlemcen'), ('Tiaret', 'Tiaret'), ('Tizi-Ouzou', 'Tizi-Ouzou'), ('Alger', 'Alger'), ('Djelfa', 'Djelfa'), ('Jijel', 'Jijel'), ('Setif', 'Setif'), ('Saida', 'Saida'), ('Skikda', 'Skikda'), ('Sidi-Bel-Abbes', 'Sidi-Bel-Abbes'), ('Annaba', 'Annaba'), ('Guelma', 'Guelma'), ('Constantine', 'Constantine'), ('Medea', 'Medea'), ('Mostaganem', 'Mostaganem'), ('M-Sila', 'M-Sila'), ('Mascara', 'Mascara'), ('Ouargla', 'Ouargla'), ('Oran', 'Oran'), ('El-Bayadh', 'El-Bayadh'), ('Illizi', 'Illizi'), ('B-B-Arreridj', 'B-B-Arreridj'), ('Boumerdes', 'Boumerdes'), ('El-Tarf', 'El-Tarf'), ('Tindouf', 'Tindouf'), ('Tissemsilt', 'Tissemsilt'), ('El-Oued', 'El-Oued'), ('Khenchela', 'Khenchela'), ('Souk-Ahras', 'Souk-Ahras'), ('Tipaza', 'Tipaza'), ('Mila', 'Mila'), ('Ain-Defla', 'Ain-Defla'), ('Naama', 'Naama'), ('Ain-temouchent', 'Ain-temouchent'), ('Ghardaia', 'Ghardaia'), ('Relizane', 'Relizane'), ('Timimoun', 'Timimoun'), ('B-B-Mokhtar', 'B-B-Mokhtar'), ('Ouled-Djellal', 'Ouled-Djellal'), ('Beni-Abbes', 'Beni-Abbes'), ('In-Salah', 'In-Salah'), ('In-Guezzam', 'In-Guezzam'), ('Touggourt', 'Touggourt'), ('Djanet', 'Djanet'), ('M-Ghair', 'M-Ghair'), ('El-Meniaa', 'El-Meniaa')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('email', models.EmailField(max_length=35, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=25)),
                ('telephone', models.IntegerField(max_length=10)),
                ('annonces', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.annonce')),
            ],
        ),
        migrations.AddField(
            model_name='annonce',
            name='photos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.photo'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='pos',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.position'),
        ),
    ]
